### ISSUE TITLE
Upon program start OnscreenOverlay "DisplayID" setting in config.json is replaced with value for only detected monitor even if configured for disconnected monitor

### ISSUE THREAD

**Issue by successtheman** [SaifAqqad/AHK_MicMute#97] opened 2024-02-03 22:28 UTC
Essentially if you have set the OnscreenOverlay to show on one monitor then disconnect or disable that monitor temporarily for whatever reason (I regularly use https://sourceforge.net/projects/monitorswitcher/ to manage my monitor layouts and switch between them), MicMute will edit and replace the previously set "DisplayID" in config.json with the currently connected monitor (not sure how it would behave if there were 2 monitors connected and the previously configured value was not able to be found but I assume it would be something similar, I have only tested with enabling just one monitor however). As a result when you reconnect the monitor, it then will be on the new monitor which was put in config.json instead of the one you had previously configured.

Would it be possible to preserve the "DisplayID" for when the monitor is reconnected once again instead of completely changing the "DisplayID" in config.json when the program detects a monitor as disconnected?

Could there be some fallback logic that doesn't edit the config.json and preserves the disconnected monitor positioning but just defaults OnscreenOverlay to the first monitor when the monitor in "DisplayID" in config.json can't be found?

**Comment by successtheman** [comment] 2024-02-03 22:32
Might be related to this and I have to change my config.json somehow? https://github.com/SaifAqqad/AHK_MicMute/issues/73#issuecomment-1636999519

**Comment by successtheman** [comment] 2024-02-07 02:20
So it appears it remembered the other monitor positioning now? I am very confused as I changed nothing 😂 this is an odd one

**Comment by SaifAqqad** [comment] 2024-02-23 06:34
Hey, I just tested the overlay position behavior, and it seems to work as intended, unless I'm misunderstanding the issue here.

When first setting up the overlay on a monitor, a relative position will be added to the config for that exact monitor (with its Id set to the monitor name and serial number)

![image](https://github.com/SaifAqqad/AHK_MicMute/assets/47293197/14a78c60-8db8-438f-a55f-d0f0f5e1748d)

Even if u add other monitors it should not replace a position for one monitor with another, only if you do move the overlay to the other monitor or disconnect the first monitor, in the former case it will immediately add a new entry for the new monitor with the relative positions u set, however in the latter case, the overlay will check if there is an entry in the `Position` array that matches the new monitor id, if there is, it will use it as is, and if there isn't, it will add a new entry for the new monitor with the same relative position of the first monitor

###### After adding a second monitor and moving the overlay onto it:
![image](https://github.com/SaifAqqad/AHK_MicMute/assets/47293197/52da4356-199a-4476-9309-04338689ec80)


Note that the entries in the `Position` array are ordered based on most recently added (i.e. the first position will be for the last monitor you changed the position on), also you can manually change the order of the positions so that one monitor would be preferred over another when both are present.

also note that there was a bug with the `DisplayId` which sometimes would fail to be retrieved and so the `DisplayId` would just be the monitor's name followed by an `_` this might cause issues if you have multiple monitors with the same name, though it should be fixed now with commit c5f3c3ef59187869deaeb08184ecebfe7cfbb2bc

**Comment by successtheman** [comment] 2024-02-29 01:25
The issue was that it forgets when you connect other monitors or disconnect them and then reconnect them and it was overwriting the `DisplayID` value. I just tested again and it seems to not remember the disconnected monitor positioning, and upon closing MicMute and opening it again (to simulate rebooting the pc). As such it has then replaced the `DisplayID` value with one of the monitors that was connected when the program was last closed instead of saving the previous value for a disconnected monitor.

**Comment by SaifAqqad** [comment] 2024-03-01 06:28
I pushed a commit (0820feadbaebcb666720b9c06f1169c1f2b5836d) that should fix this issue, the overlay will now insert a new position for the other monitor instead of replacing the original one with it.

If you want, you can test it out in the [dev build](https://github.com/SaifAqqad/AHK_MicMute/releases/tag/latest_commit).        
I will probably make a new release tomorrow though.

**Closed by SaifAqqad** 2024-03-01 06:28 UTC
Labels: bug

**Comment by successtheman** [comment] 2024-03-01 07:34
Good to know I wasn't crazy, also thanks for this great software, I used to use the original one on sourceforge (which I think inspired this one if I am not mistaken)
